paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: 이메일 존재여부 확인과 비밀번호 일치 확인후 토큰 발급
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                  description: 유저 이메일
                userPassword:
                  type: string
                  description: 유저 비밀번호
              required:
                - userEmail
                - userPassword
      responses:
        '200':
          description: 토큰 발급에 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Token generated successfully
                  token:
                    type: string
                    example: <generated_token>
        '404':
          description: db에 유저가 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: User not found
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  message:
                    type: string
                    example: Server error
  /auth/logout:
    post:
      tags:
        - Auth
      summary: "세션 파괴 및 로그아웃 처리"
      responses:
        '200':
          description: "로그아웃 성공"
        '500':
          description: "세션 삭제 중 에러"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  message:
                    type: string
                    example: "세션 삭제 중 에러"
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                  format: email
                userPassword:
                  type: string
                userNickname:
                  type: string
                userName:
                  type: string
                userPhone:
                  type: string
              required:
                - userEmail
                - userPassword
                - userNickname
                - userName
                - userPhone
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              example:
                message: '회원 가입 성공'
        '400':
          description: Bad request - Duplicate nickname or email
          content:
            application/json:
              example:
                error: '이미 사용 중인 닉네임입니다.' # or '이미 등록된 이메일 주소입니다.'
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: '서버 에러'
  /auth/resign:
    patch:
      tags:
        - Auth
      summary: 유저 삭제
      description: 유저 계정 삭제
      requestBody:
        required: true
        content:
          application/json:
                schema:
                  type: object
                  properties:
                    userEmail:
                      type: string
                      description: 유저 이메일
                    userPassword:
                      type: string
                      description: 유저 비밀번호
                  required:
                    - userEmail
                    - userPassword

      responses:
        '201':
          description: 유저 삭제 성공
          schema:
            type: object
            properties:
              message:
                type: string
                description: 유저 삭제 성공

        '500':
          description: 서버 오류
          schema:
            type: object
            properties:
              error:
                type: string
                description: 서버 오류
  /auth/email:
    post:
      tags:
        - Auth
      summary: 전화번호를 통해 사용자 이메일 찾기
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userPhone:
                  type: string
                  description: 전화번호 입력
                  example: 010-0000-0000
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                maskedEmail: masked_email@example.com
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /auth/password:
    post:
      tags:
        - Auth
      summary: Update user password
      description: Update the password of a user based on email and name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                  description: The email of the user
                user_name:
                  type: string
                  description: The name of the user
                a_password:
                  type: string
                  description: The new password for the user
      responses:
        '200':
          description: User password updated successfully
        '400':
          description: Bad request - Invalid input parameters
        '404':
          description: User not found
        '500':
          description: Internal Server Error

  /auth/sleep:
    patch:
      tags:
        - Auth
      summary: Sleep User Operation
      description: Endpoint to put a user to sleep.
      requestBody:
        description: User credentials for sleeping
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                useremail:
                  type: string
                  format: email
                  description: The email of the user to sleep
                  example: user@example.com
                userpassword:
                  type: string
                  description: The password of the user
                  example: password123
      responses:
        '200':
          description: User sleep operation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: Sleep user operation successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'