paths:
  /review/register:
    post:
      tags:
        - Review
      summary: 후기 등록
      security:
        - Authorization: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: 작성자(구매자) 아이디
                productId:
                  type: integer
                  description: 작품
                reviewContent:
                  type: string
                  description: 후기 내용
                  example: I like it!
                reviewRate:
                  type: integer
                  description: 후기 점수 (0-좋았어요, 1-그냥 그래요, 2-별로였어요)
                  example: 1
              required:
                - userId
                - productId
                - reviewContent
                - reviewRate
      responses:
        '200':
          description: 후기 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Review registed successfully"
                  data:
                    type: object
                    example: {
                      "reviewId": 0,
                    }        
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '404':
          description: db에 유저가 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: User not found
        
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: Server error
                
  /review/{reviewId}:
    get:
      tags:
        - Review
      summary: 후기 세부 내용 조회
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
            description: 후기 아이디
      responses:
        '200':
          description: 후기 정보 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    example: {
                      "reviewId": 0,
                      "productId": 0,
                      "consumerId": 0,
                      "consumerNickname": "별명",
                      "context": "리뷰 내용",
                      "rate": 0,
                      "status": 1,
                      "date": "2024-01-01 00:00:00"
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
                    
  /review/list:
    get:
      tags:
        - Review
      summary: 후기 목록 조회
      responses:
        '200':
          description: 후기 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    example: {
                      "categoryData": [
                          {
                              "productId": 100,
                              "title": "제목1",
                              "authorId": 0,
                              "authorNickname": "닉네임1",
                              "image": "imgUrl1",
                              "status": 0
                          },
                          {
                              "productId": 99,
                              "title": "제목1",
                              "authorId": 0,
                              "authorNickname": "닉네임1",
                              "image": "imgUrl1",
                              "status": 0
                          },
                          {
                              "productId": 98,
                              "title": "제목1",
                              "authorId": 0,
                              "authorNickname": "닉네임1",
                              "image": "imgUrl1",
                              "status": 0
                          }
                      ],
                      "cursorId": 98
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.