paths:
  /review/register:
    post:
      tags:
        - review
      summary: 후기 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reviewId:
                  type: integer
                  description: 후기 아이디
                productId:
                  type: integer
                  description: 작품
                title:
                  type: string 
                  description: 후기 제목
                context:
                  type: string
                  description: 후기 내용
                  example: I like it!
                rate:
                  type: integer
                  description: 후기 점수
                  example: 좋았어요
                createdAt:
                  type: DATETIME
                  description: 생성일시
                  example: YYYY-MM-DD
              required:
                - reviewId
                - productId
                - title
                - context
                - rate
                - createdAt
      responses:
        '200':
          description: 후기 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Review registed successfully"
                  data:
                    type: object
                    example: {
                      "name": "swagger",
                    }        
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
               status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: string
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다

        '404':
          description: db에 유저가 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: User not found
        
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: Server error
                
  /review/:reviewId:
    patch:
      tags:
        - review
      summary: 후기 상태 변경
      requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                  type: string
                  format: binary
                description: 삭제
              updatedAt:
                type: DATETIME
                description: 갱신일시
                example: YYYY-MM-DD
            required:
              - status
              - updatedAt
      responses:
        '200':
          description: 후기 상태 변경 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Review status deltete successfully"
                  data:
                    type: object
                    example: {
                      "status": "delete"
                    }
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
               status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: string
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다

        '404':
          description: db에 유저가 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: User not found
        
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: Server error
                 
    get:
      tags:
        - review
      summary: 후기 정보 조회
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
            description: 후기 아이디
        - in: query
          name: cursorId
          required: false
          schema:
            type: integer
            description: 없으면 가장 최근에 등록된 후기부터 불러옴.
        - in: query
          name: paging
          required: false
          schema:
            type: integer
            description: 'default: 3, 한 번에 몇 개의 데이터를 불러올 지 지정'
      responses:
        '200':
          description: 후기 정보 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
                    
  /review/list:
    get:
      tags:
        - review
      summary: 후기 목록 조회
     responses:
        '200':
          description: 후기 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.