paths:
  /test/s3:
    post:
      tags:
        - Test
      summary: 파일 업로드 테스트용
      parameters:
        - in: query
          name: directory
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: 사진 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.

  /test/db:
    get:
      tags:
        - Test
      summary: DB 조회 테스트용
      responses:
        '200':
          description: 사진 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.