paths:
  /tos/register:
    post:
      tags:
        - tos
      summary: 약관 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                utId:
                  type: integer
                  description: 사용자 약관 아이디
                utTosId:
                  type: integer
                  format: binary
                  description: 약관 아이디
                utUserId:
                  type: integer 
                  description: 사용자 아이디
                utAgree:
                  type: boolean
                  description: 약관 동의 여부
                  example: 1
                createdAt:
                  type: DATETIME
                  description: 생성일시
                  example: YYYY-MM-DD
              required:
                - utId
                - utTosId
                - utUserId
                - utAgree
                - createdAt
      responses:
        '200':
          description: 약관 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Tos registed successfully"
                  data:
                    type: object
                    example: {
                      "utId": "사용자 약관 아이디",
                      "utTosId": "약관 아이디",
                      "utAgree": "비동의"
                    }        
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
               status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: string
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다

        '404':
          description: db에 유저가 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: User not found
        
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: Server error
                
  /tos/:utId:
    patch:
      tags:
        - product
      summary: 추후 약관 동의 수정
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                utId:
                  type: integer
                  description: 사용자 약관 아이디
                utTosId:
                  type: integer
                  format: binary
                  description: 약관 아이디
                utUserId:
                  type: integer 
                  description: 사용자 아이디
                utAgree:
                  type: boolean
                  description: 약관 동의 여부
                  example: 1
                updatedAt:
                  type: DATETIME
                  description: 갱신일시
                  example: YYYY-MM-DD
              required:
                - utId
                - utTosId
                - utUserId
                - utAgree
                - updatedAt
      responses:
        '200':
          description: 약관 동의 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Tos edited successfully"
                  data:
                    type: object
                    example: {
                      "utId": "사용자 약관 아이디",
                      "utTosId": "약관 아이디",
                      "utAgree": "동의"
                    }   
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
               status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: string
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다

        '404':
          description: db에 유저가 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: User not found
        
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: Server error