paths:
  /user/{userId}/like:
    get:
      tags:
        - User
      summary: 선호 작품 불러오기
      security:
        - Authorization: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: 사용자 sequence Number
        - in: query
          name: cursorId
          required: false
          schema:
            type: integer
            description: 없으면 가장 최근의 선호 작품부터 불러옴.
        - in: query
          name: paging
          required: false
          schema:
            type: integer
            description: 'default: 3, 한 번에 몇 개의 데이터를 불러올 지 지정'
      responses:
        '200':
          description: 선호 작품 불러오기 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                  data:
                    type: array
                    example: {
                      "userLikeList": [
                        {
                            "fv_id": 1,
                            "userId": 2,
                            "favorStatus": 1,
                            "productId": 1,
                            "productName": "작품명",
                            "productAuthor": "작가명",
                            "productStatus": 1,
                            "productImg": "imgURL"
                        },
                        {
                            "fv_id": 1,
                            "userId": 2,
                            "favorStatus": 1,
                            "productId": 1,
                            "productName": "작품명2",
                            "productAuthor": "작가명2",
                            "productStatus": 0,
                            "productImg": "imgURL2"
                        }
                      ],
                      "cursorId": 2
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
    post:
      tags:
        - User
      summary: 선호 작품 등록/ 상태 변경 (좋아요 해제 혹은 재설정)
      security:
        - Authorization: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            description: 사용자 sequence Number
        - in: query
          name: productId
          required: true
          schema:
            type: integer
            description: 좋아요를 적용할 작품 ID(sequence Number) 전달
      responses:
        '200':
          description: 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                  data:
                    type: object
                    example: {
                      "id": 1,
                      "userId": 2,
                      "productId": 1,
                      "status": 1
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.

/user/{userId}:
    patch:
      tags:
        - User
      summary: 사용자 정보 수정
      security:
        - Authorization: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            description: 사용자 sequence Number
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: 이미지 파일 - 1개만 가능
                  required: false
                userNickname:
                  type: string
                  format: text
                  description: 수정할 닉네임
                  example: 수정할 닉네임
                  required: false
                userIntroduce:
                  type: string
                  format: text
                  description: 수정할 소개글
                  example: 수정할 소개글
                  required: false
      responses:
        '200':
          description: 사용자 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
                  data:
                    type: array
                    example: {
                      "userId": 00,
                      "userNickname": "닉네임",
                      "userIntroduce": "소개글",
                      "userProfile": "profileImgUrl"
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.